version: '2'
services:
    db:
        image: mongo:latest
        container_name: db
        volumes:
            - ../mongo/data:/data/db
    front:
        build: ../front
        container_name: front
        volumes:
            - ../front:/opt/tlks.io/front
            - ../front/config.json:/opt/tlks.io/front/config.json
        command: npm start
        links:
            - db:db
        depends_on:
            - db
    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - front:front
        ports:
            - "80:80"
